package lk.ijse.aad.backend.Entity;

public enum Category {
    HOME_AND_TECHNICAL_SERVICE,
    VEHICLE_SERVICE,
    IT_AND_DIGITAL_SERVICE,
    BEAUTY_AND_PERSONAL_CARE,
    HEALTH_AND_WELLNESS,
    FOOD_SERVICE,
    EVENT_AND_MEDIA,
    PROFESSIONAL_SERVICE

}